### ISSUE TITLE
Add ability for tooling server to send emails

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic.tools#166]
I am not sure of the best way to do this, but I'd like to create a node module that has an interface like this:

```
var mailman = require('mailman')

mailman.send({
    to:matt@numenta.org
  , subject: "hello"
  , body: "I love you."
}, function(err) {

});
```

I'm using `mailman` as a placeholder. Not sure what it should be named. There may be existing smtp modules available.

**Comment by passiweinberger** [comment]
If its not too urgent, I am gonna try solveing this, but have to work myself in a bit firstly ;)

**Comment by rhyolight** [comment]
That's great! Please let me know if I can help explain anything.

**Comment by passiweinberger** [comment]
:+1:

**Comment by rhyolight** [comment]
Maybe https://www.npmjs.com/package/email

**Comment by rhyolight** [comment]
Note that whatever email service we use must be available on Heroku: https://addons.heroku.com/#email-sms

**Comment by rhyolight** [comment]
I'm thinking maybe [Postmark](https://addons.heroku.com/postmark)? In that case, you may need to investigate Node.js interface options for this service.

**Comment by rhyolight** [comment]
Yes, please use Postmark. I've looked into it, and it is simple to set up and cheap. I could enable the Postmark service for use on our AWS instance of the tooling server, set up the secret key and redeploy to have it set up pretty easily. Then once we move to Heroku, we get Postmark for free (10K message a month, way more than we need).

**Comment by passiweinberger** [comment]
Haha that's exactly the tab I just opened a sec before ;D

<div>-------- Original message --------</div><div>From: Matthew Taylor <notifications@github.com> </div><div>Date:04/15/2015  18:44  (GMT+01:00) </div><div>To: "numenta/nupic.tools" <nupic.tools@noreply.github.com> </div><div>Cc: Pascal Weinberger <passiweinberger@gmail.com> </div><div>Subject: Re: [nupic.tools] Add ability for tooling server to send emails
  (#166) </div><div>
</div>Maybe https://www.npmjs.com/package/email

**Comment by passiweinberger** [comment]
What limits are OK ? For a beter long term useage? As Mandrilla has the highest limit for free usage ? 

<div>-------- Original message --------</div><div>From: Matthew Taylor <notifications@github.com> </div><div>Date:04/15/2015  18:48  (GMT+01:00) </div><div>To: "numenta/nupic.tools" <nupic.tools@noreply.github.com> </div><div>Cc: Pascal Weinberger <passiweinberger@gmail.com> </div><div>Subject: Re: [nupic.tools] Add ability for tooling server to send emails
  (#166) </div><div>
</div>I'm thinking maybe Postmark? In that case, you may need to investigate Node.js interface options for this service.

**Comment by passiweinberger** [comment]
Ok i'll try setting up Postmark then :)

**Comment by rhyolight** [comment]
@passiweinberger I just set up a Postmark account. You should receive an email invitation to join as well. I think I can give you permissions to the numenta Postmark account so you can get the credentials you need to test it. Just don't add the credentials to git. Assume it will be set in an environment variable like `POSTMARK_API_TOKEN`.

**Comment by passiweinberger** [comment]
#178

**Comment by rhyolight** [comment]
Forgot to close this. Thanks again, @passiweinberger.
