### ISSUE TITLE
Trigger AppVeyor builds for open PRs on merge to master (nupic.core)

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic.tools#174]
I'll need to find out if AppVeyor has an API. I'm triggering Travis-CI builds programmatically through their API whenever a PR merges to master so all other PRs re-build. Will need to do the same for AppVeyor.

**Comment by rhyolight** [comment]
There is an API for this: http://www.appveyor.com/docs/api/projects-builds#start-build-of-pull-request-github-only

**Comment by rhyolight** [comment]
There's no AppVeyor API client for Node.js, so I'll put a simple one together in https://github.com/rhyolight/appveyor-js-client.

**Comment by rhyolight** [comment]
I've updated the tooling server, which should now be triggering AppVeyor builds for all open pull requests for `nupic.core`.

I need to leave it running for a bit to see if it really is working, so @david-ragazzi watch for me and let me know if you think it is working.

**Comment by rhyolight** [comment]
Working!

**Comment by david-ragazzi** [comment]
@rhyolight Just a observation: tooling server is triggering for new PRs, but when something is merged on master, the builds of open PRs aren't restarted automatically.. I had to re-commit changes in order to restart the builds.

**Comment by rhyolight** [comment]
It never re-ran PR builds on merge to master, only when PRs are closed due
to a merge.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta
