### ISSUE TITLE
Automatic PR review of primary repos at certain time, closing or commenting

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic.tools#201]
Depends on #207.

Once a day, the tooling server should fetch all PRs for each primary repository and review them. 

- [x] For PRs labeled `status:in progress` or `status:help wanted` where updated over 25 days old, a warning comment should be created stating that the PR will be closed in 5 days if no further commits are pushed.
- [x] For PRs labeled `status:in progress` or `status:help wanted` where updated over 30 days old, the PR should be closed.
- [x] For PRs labeled `status:ready` where `updated_at` older than 7 days old should generate an email to the committer mailing list.

**Comment by rhyolight** [comment]
These logic would be a part of the pr-reviewer CronJob added in #212.

**Comment by brev** [comment]
cc @jcasner I'm helping Matt with this one next FYI

**Comment by brev** [comment]
@rhyolight FYI I'm back on this more seriously again, tracing around learning how it works, getting close to making some real edits I think.

**Comment by rhyolight** [comment]
Ok, I'm open for questions anytime.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by brev** [comment]
Work done, ready for review on PR #213

**Comment by rhyolight** [comment]
@brev fixed in #213, but I'm going to wait until I see it working before I close this issue.
