### ISSUE TITLE
Only warn and close PRs that are labeled as "ready"

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic.tools#214]
Currently, our PR review logic seems to add warnings and close PRs whether they are labeled as `status:ready` or otherwise. It should only warn and close PRs due to inactivity if they have the `status:ready` label applied to them. Other PRs should be left alone because we'll assume they are still awaiting review. 

See https://github.com/numenta/nupic.core/pull/361#issuecomment-125730076 for an example.

**Comment by brev** [comment]
ok, just to confirm, the description at https://github.com/numenta/nupic.tools/issues/201is wrong then? thanks

**Comment by rhyolight** [comment]
I'm sorry, the original logic was correct. My brain is wrong.

**Comment by brev** [comment]
:)
